### ISSUE TITLE
paramiko.ssh_exception.AuthenticationException: Authentication failed. (

### ISSUE THREAD

**Issue by valdr** [sebrupik/csc_scripts#2]
Hello again,

The script throws the above error now.
Tht traceback is as follows:

> (sebrupik) [tdadmin@nl-ehv-torvalds sebrupik]$ python3 configbup.py -c switchlist.csv
> SSH username: mspadmin
> SSH Password:
> Server username:mspadmin
> Server SSH Password:
> +++++ 10.100.100.46 +++++
> Timed-out reading channel, data not available.
> Traceback (most recent call last):
>   File "configbup.py", line 80, in <module>
>     main()
>   File "configbup.py", line 73, in main
>     ssh_client.connect(REMOTE_SERVER_IP, username=remote_username, password=remote_password)
>   File "/home/tdadmin/.local/share/virtualenvs/sebrupik-MSXbSfC-/lib/python3.6/site-packages/paramiko/client.py", line 446, in connect
>     passphrase,
>   File "/home/tdadmin/.local/share/virtualenvs/sebrupik-MSXbSfC-/lib/python3.6/site-packages/paramiko/client.py", line 764, in _auth
>     raise saved_exception
>   File "/home/tdadmin/.local/share/virtualenvs/sebrupik-MSXbSfC-/lib/python3.6/site-packages/paramiko/client.py", line 751, in _auth
>     self._transport.auth_password(username, password)
>   File "/home/tdadmin/.local/share/virtualenvs/sebrupik-MSXbSfC-/lib/python3.6/site-packages/paramiko/transport.py", line 1509, in auth_password
>     return self.auth_handler.wait_for_response(my_event)
>   File "/home/tdadmin/.local/share/virtualenvs/sebrupik-MSXbSfC-/lib/python3.6/site-packages/paramiko/auth_handler.py", line 250, in wait_for_response
>     raise e
> paramiko.ssh_exception.AuthenticationException: Authentication failed.
> (sebrupik) [tdadmin@nl-ehv-torvalds sebrupik]$

I was wondering about this:
When I use SSH directly to connect to the SRX, I get in using only one set of username/password. Why does it ask for it twice?

**Comment by sebrupik** [comment]
Hello again, the second username and password is for the server which the script will attempt to scp the tar.gz file to once all the items in the CSV have been parsed.

If you don't want that feature comment out lines 33-34 and 68-73.

**Comment by valdr** [comment]
A-HA! so the first set is for the remote server, and the second is for the local server... or a third server I'd want to save it to?

**Comment by sebrupik** [comment]
Yes, the first set is for every device listed in the CSV and the second is for the SCP server where the tar file is to be copied.
